---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: aiidalab-storage
    annotations:
        cas.openebs.io/config: |
            - name: StorageType
              value: "hostpath"
            - name: BasePath
              value: /var/aiidalab-microk8s/storage
        openebs.io/cas-type: local
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
