---
proxy:
  service:
    loadBalancerIP: 10.64.140.44
singleuser:
    image:
        name: "docker.io/aiidalab/full-stack"
        tag: "2023.1008"
        pullPolicy: "Always"
    cmd: null
    extraEnv:
        AIIDALAB_DEFAULT_APPS: "quantum-espresso==23.1.0b0"
        JUPYTERHUB_SINGLEUSER_APP: "notebook.notebookapp.NotebookApp"
    storage:
        dynamic:
            storageClass: aiidalab-storage
    memory:
        guarantee: 2G
    cpu:
        guarantee: 2
hub:
    db:
        pvc:
            storageClassName: aiidalab-storage
    extraConfig:
        myConfig: |
            c.KubeSpawner.http_timeout = 120
    config:
        Authenticator:
            admin_users:
                - admin
                - jyu
        NativeAuthenticator:
            ask_email_on_signup: true
            check_common_password: true
            minimum_password_length: 10
        JupyterHub:
            authenticator_class: nativeauthenticator.NativeAuthenticator
